### ISSUE TITLE
Training scripts for the architectures

### ISSUE THREAD

**Issue by xingchenwan** [automl/nasbench301#13]
Hi all,

Many thanks for the great work! 

I am aware that the training logs of the architectures used as train data for the surrogate in NAS-Bench-301 are released, but I'm wondering whether I could access the original scripts used to train the architectures from scratch? I appreciate that the training details are mentioned in App A of the paper, but with some additional augmentations used (e.g. MixUp) compared to standard DARTS procedure, I think it'd be great if I could use the exact original training script used to construct the benchmark.

If they are already in the repo, I'd be grateful if you could point me to the right place.

Many thanks in advance for your help.

Xingchen

**Comment by arberzela** [comment]
Hi Xingchen,

I just uploaded the training script at `nasbench301/data_generation/`. Since we have been using an older version of Auto-PyTorch for that I uploaded that in a new branch at the Auto-PyTorch repository and updated the `requirements.txt` file here to automatically install that version. I updated the README.md with the necessary instructions to run the architecture training.

Let me know if you face any issues.

Cheers,
Arber
